name: on-tag
on: 
  push:
    tags:
      - '*'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.4' # The Go version to download (if necessary) and use.
      - run: go version
      - run: go get github.com/cucumber/godog/cmd/godog
      - run: godog
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - run: echo $RELEASE_VERSION
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: service:$RELEASE_VERSION